const TABLE_PAGE_SIZE = 10;
const UPLOAD_PATH_PREFIX = ".";
const SHARE_LINK_PREFIX = "/share/doc/";
const GITHUB_URL = process.env.GITHUB_PROFILE;
const WHATSAPP_URL = process.env.WHATSAPP_MESSAGE_URL;
const LINKEDIN_URL = process.env.LINKEDIN_PROFILE_URL;

export {
  TABLE_PAGE_SIZE,
  SHARE_LINK_PREFIX,
  UPLOAD_PATH_PREFIX,
  GITHUB_URL,
  WHATSAPP_URL,
  LINKEDIN_URL,
};
